require "vish.plugins-setup"
require "vish.core.options"
require "vish.core.keymaps"
require "vish.core.colorscheme"

require "vish.plugins.comment"
require "vish.plugins.nvim-tree"
require "vish.plugins.lualine"
require "vish.plugins.telescope"
require "vish.plugins.nvim-cmp"
require "vish.plugins.lsp.mason"
require "vish.plugins.lsp.lspsaga"
require "vish.plugins.lsp.lspconfig"

require "vish.plugins.lsp.null-ls"
